data/soapvalidator/MailClient/Mail/Bugs/ZBUG-451.xml
Sent a mail with subject containing  =?us-ascii?Q? in the subject.
On receiver, verified the subject does not contain the above encoded chars
=> Automation for ZBUG-451 for us-ascii encoded chars

README.md, build.xml, ivy.xml
Updated xerces jar to version 2.9.1-patch-01 and README of the repo.
=> ZCS-5267: Updated xerces jar to version 2.9.1-patch-01 and README of the repo

data/soapvalidator/Admin/PrimaryEmailAddressChange/ZCS-5359.xml
Added test cases covering the basic positive and negative scenarios for new API introduced ChangePrimaryEmailRequest
=> Automation for ChangePrimaryEmailRequest API

data/soapvalidator/MailClient/HAB/ZCS-5705_ZimbraHABOu.xml
Automation added for HABOrgUnitRequest.
Added positive and negative cases
=> Automation for ZCS-5705 for Create HAB Org unit request

data/soapvalidator/MailClient/HAB/ZCS-5394_CreateHABGroup.xml
Automation for CreateHABGroup request.
Added positive and negative scenarios.
Tests added for static and dynamic groups.
Test added for non ascii group name
=> Automation for ZCS 5394 for Create HAB Group request

data/soapvalidator/MailClient/HAB/ZCS-5396_AddHABMember.xml
Automation added for AddDistributionLIstMembersRequest
Covered all cases mentioned in testrail 
http://testrail01.buf.synacor.com/testrail/index.php?/cases/view/1418932
=> Automation for Add HAB Members request

data/soapvalidator/MailClient/HAB/ZCS-5709_GetDistributionListMembers.xml
Added automation cases for fetching HAB members from static/dynamic groups.
Added cases to get the members based on seniority index.
=> Automation for ZCS-5709 for GetDLMembersRequest for HAB groups

data/soapvalidator/MailClient/HAB/ZCS-5397_GetHABGroups.xml
Added automation for GetHABGroups for static/dynamic groups.
Check for non hab groups.
Sorting of groups based on seniority index.
=> Automation for ZCS-5397 for GetHABGroups

data/soapvalidator/MailClient/HAB/ZCS-5398_RestrictOU.xml
Added a single case in automation for cross OU HAB group restriction.
=> Automation for ZCS-5398 restrict cross OU HAB group addition

data/soapvalidator/MailClient/AddressList/ZCS-5847_CreateAddressList.xml
Added positive and negative cases for CreateAddressList Request.
Test case reference:
http://testrail01.buf.synacor.com/testrail/index.php?/cases/view/1506141f
=> Automation for ZCS 5847 for Create Address List

data/soapvalidator/MailClient/AddressList/ZCS-5387_DeleteAddressList.xml
Added cases for DeleteAddressList request for deleting the address list from ldap.
Added positive/negative cases
=> Automation for ZCS 5387 for DeleteAddressList Request

data/TestMailRaw/license/license01.xml, data/TestMailRaw/license/license02.xml
Updated license files with latest one.
Report can be found below : 
[license_info.txt](https://github.com/Zimbra/zm-soap-harness/files/2513677/license_info.txt)
=> Updated licenses as old licenses had expired

build.xml, ivy.xml
Fixed issue with jar packaging
Updated guava version from 13 to 23.
Below zip has execution reports: 
[Dav.zip](https://github.com/Zimbra/zm-soap-harness/files/2524396/Dav.zip)
=> Zcs 6049: Investigation of Dav soap automation failures on latest develop build.

.circleci/config.yml
=> config changes

data/soapvalidator/MailClient/Calendar/Appointments/CancelAppointmentRequest_Basic.xml, data/soapvalidator/MailClient/Calendar/Appointments/CreateAppointmentRequest_EmailReminder.xml, data/soapvalidator/MailClient/Calendar/Appointments/CreateAppointmentRequest_Private.xml
I have fixed following test cases which are failing due to timezone issue.
/opt/qa/soapvalidator/data/soapvalidator/MailClient/Calendar/Appointments/CancelAppointmentRequest_Basic.xml
/opt/qa/soapvalidator/data/soapvalidator/MailClient/Calendar/Appointments/CreateAppointmentRequest_EmailReminder.xml
/opt/qa/soapvalidator/data/soapvalidator/MailClient/Calendar/Appointments/CreateAppointmentRequest_Private.xml
=> Fixed timezone issues

data/soapvalidator/Admin/Bug/bug11299.xml, data/soapvalidator/MailClient/Search/Junk/search_junk.xml
Fixed files :
data/soapvalidator/Admin/Bug/bug11299.xml
data/soapvalidator/MailClient/Search/Junk/search_junk.xml
Reports:
[bug11299.txt](https://github.com/Zimbra/zm-soap-harness/files/2580222/bug11299.txt)
[search_junk.txt](https://github.com/Zimbra/zm-soap-harness/files/2580223/search_junk.txt)
=> fixed data issues

.circleci/config.yml
Below is the published artifact after a successful build: 
https://121-127704256-gh.circle-artifacts.com/0/home/circleci/repo/zm-soap-harness/soapvalidator/MailClient/Auth/auth_basic.txt
=> Added workflow to execute test on aws instance

build.xml
Adding a new property for specifying type of tests i.e. smoke, feature, negative, functional and so on.
Testing Done as below:
ant Run-SoapTestCore -DtestRoot="data/soapvalidator/MailClient/Auth" -DtestType=negative
ant Run-SoapTestCore -DtestRoot="data/soapvalidator/MailClient/Auth" -DtestType=smoke
ant Run-SoapTestCore -DtestRoot="data/soapvalidator/MailClient/Auth" -DtestType=functional
ant Run-SoapTestCore -DtestRoot="data/soapvalidator/MailClient/Auth" -DtestType=feature
=> Update build.xml to add test Type property

conf/skipped-tests-zimbrax.txt, data/soapvalidator/Admin/General/FixCalendarTZRequest-Basic.xml, data/soapvalidator/Calendar/Appointments/Alarm/DismissCalendarItemAlarmRequest.xml, data/soapvalidator/Calendar/Appointments/CounterAppointment/CounterAppointmentRequest.xml, data/soapvalidator/Calendar/Appointments/CounterAppointment/DeclineCounterAppointmentRequest.xml, data/soapvalidator/Calendar/Bugs/Bug71713.xml, data/soapvalidator/Calendar/CalendarRequest.xml, data/soapvalidator/Calendar/FreeBusy/GetWorkingHoursRequest.xml, data/soapvalidator/Settings/Filters/FilterRulesRequest.xml, data/soapvalidator/Settings/Filters/Outgoing/ApplyOutgoingfilterRules-Basic.xml
- Skipped one of the test failed because of staf and fixed old typo.
```
/opt/soap/zm-soap-harness/build/temp/data/soapvalidator/Settings/ForwardedMail/ZimbraPrefMailForwardingAddress.xml threw an exception
[java] com.zimbra.qa.soap.SoapTestCore$HarnessException: smtpinjecttest requires staf
[java] 	at com.zimbra.qa.soap.SmtpInjectTest.executeTest(SmtpInjectTest.java:239)
[java] 	at com.zimbra.qa.soap.SoapTestCore.doTest(SoapTestCore.java:946)
[java] 	at com.zimbra.qa.soap.SoapTestCore.doTestCase(SoapTestCore.java:1077)
[java] 	at com.zimbra.qa.soap.SoapTestCore.doTests(SoapTestCore.java:797)
[java] 	at com.zimbra.qa.soap.SoapTestCore.runTestFile(SoapTestCore.java:434)
[java] 	at com.zimbra.qa.soap.SoapTestMain.execute(SoapTestMain.java:485)
[java] 	at …
```
=> Skipped one of the test failed because of staf and fixed old typo

conf/skipped-tests-zimbrax.txt, conf/skipped-tests.txt, data/soapvalidator/Search/DelayedIndexing/ZCS-8515-8517.xml, data/soapvalidator/Search/DelayedIndexing/ZCS-8516.xml
Added DelayedIndexing tests
Also modified skipped files
=> Including develop branch changes for Delayed Indexing tests to zimbrax branch

conf/skipped-tests-zimbrax.txt, data/soapvalidator/Contacts/GAL/ZCS-455.xml, data/soapvalidator/Folders/Folder-Retention-Policy.xml
Executed Smoke tests and fixed/skipped follwoing failed tests.
Total Executed: 351
Total Passed: 342
Total Failed: 9
Script Errors: 24
**Failed Tests:**
build/temp/data/soapvalidator/Admin/GAL/GALRequest.xml  :**ZCS-8853 :Regression**
build/temp/data/soapvalidator/Calendar/Resources/CalendarResource.xml: **ZCS-8393**
build/temp/data/soapvalidator/Contacts/AutoComplete/AutoCompleteRequesti18n.xml"**zcs-7999**
build/temp/data/soapvalidator/Contacts/AutoComplete/Ranking/AutoComplete-GAL-Ranking.xml: **ZCS-6163**
build/temp/data/soapvalidator/Contacts/GAL/ZCS-455.xml : **Fixed : script issue: /home/ubuntu/ZCS-455.xml --Removed server="${server.zimbraAdmin}"**
build/temp/data/soapvalidator/Folders/Folder-Retention-Policy.xml : **Fixed Script Issue:Delay after FolderActionRequest** …
=> Fixed Smoke tests from zcs-9234

.github/CODEOWNERS, src/java/com/zimbra/qa/soap/TestCase.java
Need to avoid error like:
http://ci.synacor.tk:30081/test-reports/shellchecksoapbat/f5faf0f1-f006-440c-bfd5-4d5bf5de036a/smoke-soap/result-1.txt
```
***************************************************************************************
EXECUTING TEST: /opt/soap/zm-soap-harness/build/temp/data/soapvalidator/Admin/Rights/CheckRightRequest.xml
Given value for type attribute does not match expected value.
com.zimbra.qa.soap.SoapTestCore$HarnessException: Given value for type (bhr-temp) attribute does not match expected value.
at com.zimbra.qa.soap.TestCase.getType(TestCase.java:112)
at com.zimbra.qa.soap.TestCase.hasType(TestCase.java:183)
at com.zimbra.qa.soap.TestCase.shouldSkip(TestCase.java:321)
at com.zimbra.qa.soap.SoapTestCore.doTestCase(SoapTestCore.java:1007)
at …
```
=> Add -temp type to avoid exception and preserving group type

data/soapvalidator/Admin/Accounts/account_migration.xml
Small fix....Subject criteria has changed from specific folder to all folder.
=>  Refactored code for search

data/soapvalidator/Admin/COS/COS.xml, data/soapvalidator/Admin/DistributionList/Distributionlist-Action-Add-Remove-Member.xml, data/soapvalidator/Admin/Server/Status/GetServiceStatus.xml, data/soapvalidator/Auth/ZCS-4904-EndAllSession.xml, data/soapvalidator/Calendar/Privacy/Appointment-Privacy-Basic.xml, data/soapvalidator/Calendar/Resources/Resources-AutoAccept.xml, data/soapvalidator/Contacts/Bugs/GetContacts-ZCS-6232.xml, data/soapvalidator/Contacts/GAL/Bug79965.xml
Fixed following tests Which are falling in BHR run due to various reasons,
-I have have fixed/added bugid for existing bugs/added small wait etc. 
```
data/soapvalidator/Admin/COS/COS.xml
data/soapvalidator/Admin/DistributionList/Distributionlist-Action-Add-Remove-Member.xml
data/soapvalidator/Admin/Server/Status/GetServiceStatus.xml
data/soapvalidator/Auth/ZCS-4904-EndAllSession.xml
data/soapvalidator/Calendar/Privacy/Appointment-Privacy-Basic.xml
data/soapvalidator/Calendar/Resources/Resources-AutoAccept.xml
data/soapvalidator/Contacts/Bugs/GetContacts-ZCS-6232.xml
data/soapvalidator/Contacts/GAL/Bug79965.xml
```
=> Fixes as well added bug id and skip tag to  respective test

conf/skipped-tests-zimbrax.txt, data/soapvalidator/Admin/DistributionList/Distributionlist-Action-Add-Remove-Member.xml, data/soapvalidator/Calendar/Appointments/ForwardAppointmentInviteRequest-Basic.xml, data/soapvalidator/Folders/Searchfolder-Create.xml, data/soapvalidator/Mail/LMTP/AOL/AOL-MIME-Basic.xml, data/soapvalidator/Sync/Bugs/Bug96696.xml
Fixed following consistent failures.
```
conf/skipped-tests-zimbrax.txt
data/soapvalidator/Admin/DistributionList/Distributionlist-Action-Add-Remove-Member.xml
data/soapvalidator/Calendar/Appointments/ForwardAppointmentInviteRequest-Basic.xml
data/soapvalidator/Folders/Searchfolder-Create.xml
data/soapvalidator/Mail/LMTP/AOL/AOL-MIME-Basic.xml
data/soapvalidator/Sync/Bugs/Bug96696.xml
```
=> Fixed bhr failed tests

data/soapvalidator/Admin/Bugs/zbug2026.xml
Issue :zimbraCoSId not showing when it's inheriting from domain level.
=> Added automation for zbug2026

data/soapvalidator/Admin/Auth/AdminAuth_basic.xml
Added automation for Admin auth with out password.
=> Added test case for zbug-2500

data/soapvalidator/Admin/Auth/AdminAuth-Basic.xml
Added test case for zbug2500: admin auth without password
=> Added test case for zbug2500

data/soapvalidator/Calendar/Resources/Resources-AutoAccept.xml
Testing:
```
STAF LOCAL soap EXECUTE zqa-373.eng.zimbra.com ZIMBRAQAROOT /opt/qa/soapvalidator/ DIRECTORY /opt/qa/soapvalidator/data/soapvalidator/Calendar/Resources/Resources-AutoAccept.xml LOG /opt/ SUITE BHR
--------
Executed:2
Pass:2
Fail:0
Script Errors:0
```
=> ZCS-11674: Fixed failing calendar test due to lapsed date used in testcase

data/soapvalidator/Mail/Attachments/Message-Send-WAttach-WScanEnabled.xml
ZBUG-3129 adding soap harness test for the email with attachment scanning enabled.
=> ZBUG-3129: Add soap harness test for the email with attachment scan

data/soapvalidator/Auth/ForgetPassword/ZCS-4798.xml, data/soapvalidator/Auth/ForgetPassword/ZCS-4800.xml, data/soapvalidator/Calendar/Appointments/CreateAppointmentRequest-Reminder.xml, data/soapvalidator/Tasks/Get-Tasks.xml
**Fix following failing test cases in soap run:**
- data/soapvalidator/Auth/ForgetPassword/ZCS-4798.xml
- data/soapvalidator/Auth/ForgetPassword/ZCS-4800.xml
- data/soapvalidator/Calendar/Appointments/CreateAppointmentRequest-Reminder.xml
- data/soapvalidator/Tasks/Get-Tasks.xml
=> ZCS-14938: Fix BHR SOAP failures

utils/run_and_monitor_soap.sh
**ZCS-14958: Add a fuction to build soapdata.tar file to run and monitor script.**
New function added to the script -
- Checks if directory `/opt/qa/soapvalidator` exists.
- If Yes, then will use the present soapdata for testing.
- If No, then checks if the server has `GITHUB_ACCESS_TOKEN` and clones the required repos to build new soapdata.tar
Note: If you do not wish to use old soapdata.tar you must delete the contents of `/opt/qa/` and run the script.
=> ZCS-14958: Add a fuction to build soapdata.tar file to run and monitor script.

utils/run_and_monitor_soap.sh
`STAF LOCAL soap EXECUTE localhost ZIMBRAQAROOT /opt/qa/soapvalidator/ DIRECTORY /opt/qa/soapvalidator/data/soapvalidator/Dav/CalDav/Calendar/Appointments/CreateAppointment.xml LOG /opt/soaprun-test/ SUITE BHR`
`staf local soap query not returning anything`, it is in hang state. 
had checked with other test case `STAF LOCAL soap EXECUTE localhost ZIMBRAQAROOT /opt/qa/soapvalidator/ DIRECTORY /opt/qa/soapvalidator/data/soapvalidator/Contacts/AutoComplete/ LOG /opt/soaprun-test/ SUITE BHR` executing properly .
but when I run `Dav/CalDav/Calendar/Appointments/CreateAppointment.xml` it is not responding.
This has been resolved by running soap automation with the `root` user.
=> ZCS-15604 : Fix SOAP tests execution issues

data/soapvalidator/Contacts/AutoComplete/AutoComplete-ZBUG-4317.xml
**Added test cases to validate ZBUG-4317**
1. Verify AutoCompleteRequest for account matching with contact with a firstname containing an email address and no email address in the email field
2. Verify AutoCompleteRequest for account matching with contact with a firstname and lastname and no email address in the email field
Test script result:
XML: C:\soap\zm-soap-harness\data\soapvalidator\Contacts\AutoComplete\AutoComplete-ZBUG-4317.xml
CreateContactRequest                                612          2            306
AuthRequest                                         513          3            171 …
=> ZBUG-4317: Added test cases to validate AutoComplete functionality which was failing due to ZBUG-4317

data/soapvalidator/Mail/Persona/SendAsMailUsingPersonafromninexistingmailid.xml
Added test cases to validate ZBUG-4384
varify "Send Later" scheduled messages not disappear without sending when using a nonexistent email address for "zimbraAllowFromAddress"
Test script result:
-------------------FILE INFO---------------------
XML: C:\SOAP\zm-soap-harness\data\soapvalidator\Mail\Persona\SendAsMailUsingPersonafromninexistingmailid.xml
Request Name                 ExecutionTime(msec)    ExecutionCount    AvgExecutionTime(msec)
-----------------------------------------------------------------------------------
AuthRequest                                 82                    3                   27
CreateAccountRequest              847                    2                  423 …
=> ZBUG-4384:Added test cases to validate Send Later functionality which was failing

conf/global.properties, src/java/com/zimbra/qa/chat/ChatServerSoapClient.java, src/java/com/zimbra/qa/soap/SoapTest.java, src/java/com/zimbra/qa/soap/TestCase.java
ZCS-17241: Support for chat related test cases
=> ZCS-17241: Support for chat related test cases
