Zimbra/zm-soap-harness

- data/soapvalidator/MailClient/Prefs/ZCS-90.xml
All tests except for multinode test case mentioned in the below link have been automated in this test:
http://testrail01.buf.synacor.com/testrail/index.php?/cases/view/1272290
Execution report can be found here :
[ZCS-90.txt](https://github.com/Zimbra/zm-soap-harness/files/2191795/ZCS-90.txt)
> Zcs 90 :  Introduce default calendar preference attribute

- build.xml
- conf/setup.sh
All certificates setup script will be kept in zm-network-soap-harness repository.
If network folder exists then these files will be copied to zm-soap-harness/conf folder and certs can be installed using setup.sh script.
> Zcs 5593: Create bash script to configure test server before soap execution.

- data/soapvalidator/MailClient/Search/Bugs/SortBy_ZCS-3705.xml
Added one more scenario to cover readAsc, readDesc scenario.
This scenario also makes sure that passing 'sortval' attribute in 'cursor' element does not break the sort feature. 
Report can be found below : 
[SortBy_ZCS-3705.txt](https://github.com/Zimbra/zm-soap-harness/files/2218042/SortBy_ZCS-3705.txt)
> Zbug 563: Mail list keep scrolling when sorted with All/Unread

- build.xml
We will maintain two versions for global.properties file.
FOSS version will be void of properties related to Network features related properties.
And if Network edition of the code being used for testing global.properties file from conf folder will be deleted from FOSS code and it will be replaced by network edition.
> Zcs 5587: Modify build process to maintain separate global.properties file for FOSS and Network version

- data/soapvalidator/MailClient/Search/search.browseby.xml
BrowseRequest requests fail at time of running, then some of them pass later.
Introducing enough time for Solr to commit to the index appears to fix this for BrowseRequest
by "domains" or "attachments" (although not get by "objects" but that doesn't work at all yet)
> ZCS-5491:delays to allow indexing

- data/soapvalidator/MailClient/Search/search.browseby.xml
As a result of zimlets being disabled, BrowseRequest with
browseBy="objects" will always return an empty list.  This is because
indexing information is only added if any object handlers find matches
in the text and object handlers come from zimlets, so if there are no
zimlets, there are no object handlers.
Updated test to just check that a response is returned rather than expecting a list entry.
> ZCS-5491:browseBy="objects" returns no hits

- data/soapvalidator/Admin/AddressList/ZCS-5872_GetAddressListAdminAPI.xml
Scenarios covered : 
1. GetAllAddressLists request on domain that has few valid active/inactive Als
2. GetAllAddressLists request on domain that has no Als
3. GetAllAddressLists request on domain that has no active Als
4. GetAllAddressLists request without specifying domain element
5. GetAllAddressLists request on domain that has been deleted
Automation report can be verified below : 
[ZCS-5872_GetAddressListAdminAPI.txt](https://github.com/Zimbra/zm-soap-harness/files/2374562/ZCS-5872_GetAddressListAdminAPI.txt)
> ZCS-5872: Admin API to get all address lists for given domain

- data/soapvalidator/MailClient/AddressList/ZCS-5389_GetAllAddressLists.xml
Scenarios covered : 
1. GetAllAddressLists request on domain that has few valid active/inactive Als
2. GetAllAddressLists request on domain that has no Als
3. GetAllAddressLists request on domain that has no active Als
Execution report can be verified below : 
[ZCS-5389_GetAllAddressLists.txt](https://github.com/Zimbra/zm-soap-harness/files/2374529/ZCS-5389_GetAllAddressLists.txt)
> ZCS-5389 : API to get all address lists for domain

- data/soapvalidator/MailClient/Search/Bugs/SortBy_ZCS-3705.xml
1. Corrected indentation
2. Added one more test case to verify searchResponse for query 'is:unread/read' when sortby option is not provided.
Automation report can be verified below : 
[SortBy_ZCS-3705.txt](https://github.com/Zimbra/zm-soap-harness/files/2382180/SortBy_ZCS-3705.txt)
> Zcs 5871:Fix NPE caused when sortBy attribute is not sent in a Search req for is:unread

- conf/global.properties
- data/soapvalidator/MailClient/Calendar/Bugs/Bug28615.xml
- data/soapvalidator/MailClient/Calendar/Bugs/bug38478.xml
- data/soapvalidator/MailClient/Calendar/Bugs/bug45757.xml
- data/soapvalidator/MailClient/Calendar/Bugs/bug55317.xml
- data/soapvalidator/MailClient/Calendar/Bugs/bug59163.xml
- data/soapvalidator/MailClient/Calendar/Bugs/bug62674.xml
- data/soapvalidator/MailClient/Calendar/Bugs/bug87690.xml
- data/soapvalidator/MailClient/Contacts/Bugs/bug77914.xml
- data/soapvalidator/MailClient/GAL/GALAccount/Resources/SearchGalRequest.xml
- data/soapvalidator/MailClient/Mail/Bugs/bug59304.xml
- data/soapvalidator/MailClient/Mail/Bugs/bug97339.xml
- data/soapvalidator/RestServlet/Calendar/Post/basic.xml
As of now Solr commit policy is set as follows:
MAILBOX_SOFT_COMMIT_TIME=-Dsolr.mailbox.autoSoftCommit.maxTime=5000
MAILBOX_SOFT_COMMIT_DOCS=-Dsolr.mailbox.autoSoftCommit.maxDocs=-1
Because of this, SearchResponse is not being returned if we make a SearchRequest immediately after the item creation. Added a delay of 5 secs before SearchRequest for now so that SearchResponse is returned. The amount of delay can be reduced when MAILBOX_SOFT_COMMIT_TIME is reduced.
Add `solrcommitdeplay.sec` in `conf/global.properties` to consider delay as per solr commit policy.
We could not replace SearchRequest with the corresponding get--Request as items is getting created by one account and it is being searched by another account. To get the item ids, we need to make 
a SearchRequest first. 
Fixed test …
> ZCS-4785:Added delay before SearchRequest so that SearchResponse becomes available.

- data/soapvalidator/Admin/DevUnitTest/UnitTestRequest.xml
Removed unit tests as soap run should not execute unit tests.
It should be executed before creating the build
> Deprecated unit tests

- data/soapvalidator/MailClient/Mail/Bugs/bug75006.xml
Corrected data
The report can be viewed below : 
[bug75006.txt](https://github.com/Zimbra/zm-soap-harness/files/2594164/bug75006.txt)
> Data correction

- data/soapvalidator/MailClient/Identities/bugs/ZBUG-1292.xml
Steps automated:
1. Add delegate for account 1
2. Create persona for account2
3. Use persona to send email with attachment
4. Validate that the email is sent, is present in recipient's inbox and is deleted from senders draft folder.
[ZBUG-1292.txt](https://github.com/Zimbra/zm-soap-harness/files/4045072/ZBUG-1292.txt)
> ZBUG-1292: A user is not able to send an email using send-as (persona) with an attachment

- data/soapvalidator/MailClient/Misc/getinfo_request.xml
Attributes:
zimbraFeatureMobileAppEnabled
zimbraFeatureModernDesktopEnabled
Automated scenarios:
1. Setting attributes on account level and verifying the same in createAccountResponse, GetInfoResponse.
2. Setting attributes on COS, creating an account on same COS but modifying one of the attribute on account level and validating the same in createAccountResponse, GetInfoResponse.
[getinfo_request.txt](https://github.com/Zimbra/zm-soap-harness/files/4158165/getinfo_request.txt)
> Add new Feature enable attributes for Zimbra 9

- data/soapvalidator/Admin/GAL/SyncGalAccountRequest.xml
Add automation to Validate permission denied is thrown if domains are different for galsync account and authenticated account.
attached test case result - 
[SyncGalAccountRequest.txt](https://github.com/Zimbra/zm-soap-harness/files/4212804/SyncGalAccountRequest.txt)
> ZBUG-1094: Broken GAL search filtering.

- build.xml
- src/java/com/zimbra/qa/soap/SoapTestMain.java
Fix path issue for skipping tests with -sf option
Adding new property in build.xml for testRootOption to be either 'f' or 'sf'. Default being 'sf'
i.e. 
```
Option f = new Option("f", "file", true, "input document or directory");
Option sf = new Option("sf", "runSelective", true, "execute tests scripts mentioned in a file");
```
It means we can support Zimbra 9 as well as Zimbra Cloud using this property option 
For zimbra 9
```
ant Run-SoapTestCore -DtestRootOption='f' -DtestSuite='smoke' -DtestRoot='build/temp/data/soapvalidator/' 
```
for Zimbra Cloud
```
ant Run-SoapTestCore -DtestRootOption='sf' -DtestSuite='smoke' -DtestRoot='build/temp/data/soapvalidator/' 
```
Currently, for Zimbra Cloud - list of test cases to be skipped is added here - …
> Add skip tests logic

- data/soapvalidator/MailClient/Calendar/Bugs/bug62368.xml
Soap test: data/soapvalidator/MailClient/Calendar/Bugs/bug62368.xml is failing due to hard code password value: test123.
Admin has created account with default password and same account tried to authenticate with hard coded pwd as test123
Executed after change
[java] EXECUTING TEST: /opt/soap/zm-soap-harness/build/temp/data/soapvalidator/MailClient/Calendar/Bugs/bug62368.xml
[java]
[java] REQUEST/RESPONSE Results: 12(PASS) - 0(Fail)
[java]
[java]
[java] Tests Executed:12
[java] Pass:12
[java] Fail:0
> replace hardcoded pwd value and read it from global properties

- data/soapvalidator/MailClient/Search/DelayedIndexing/ZCS-8515-8517.xml
- data/soapvalidator/MailClient/Search/DelayedIndexing/ZCS-8516.xml
Added ZCS-8515-8517.xml for disable/enable indexing scenarios. 
Added ZCS-8516.xml for auto-delete of index based on lastlogintimestamp and zimbraDelayedIndexInactiveAccountAge 
**Covered below usecases:**
- disableIndexing using ManageIndexRequest API and verify indexes are deleted 
- enableIndexing using ManageIndexRequest API and verify indexing is re-enabled
- Indexing is re-enabled for account with disabled indexing after login
- Indexing is re-enabed for account with disabled indexing after admin does Delegated auth and performs search. This test will need further modification to do flushcache on all mailbox pods before DelegateAuthRequest which would be handled in separate PR.
- Account's indexing is disabled and auto-deleted if account is inactive for period greater than …
> ZCS-8876: Added SOAP automation tests for Delayed indexing feature tickets

- src/java/com/zimbra/qa/soap/SoapTestMain.java
Verified the fix by executing 2 test cases in auth.txt (one of which is Preauth)
```
root@soap-bat-1:/opt/soap/zm-soap-harness# cat conf/auth.txt
build/temp/data/soapvalidator/REST/Auth/Preauth/Admin/Preauth.xml
build/temp/data/soapvalidator/Search/Basic/Search-String-Comparison.xml
root@soap-bat-1:/opt/soap/zm-soap-harness# ant -DtestRoot="/opt/soap/zm-soap-harness/conf/auth.txt" -DtestRootOption="sf" Run-SoapTestCore
...
...
...
...
Run-SoapTestCore:
[echo] STAF: Executing /opt/soap/zm-soap-harness/conf/ooo.txt smoke
[java] 24 Apr 2020 09:36:47,514 [util.Log][main] :: WARN   local config file `/opt/zimbra/conf/localconfig.xml' is not readable
[java] ***************************************************************************************
[java] EXECUTING TEST: …
```
> TestProperties class re-initialization for -sf option used in parellelism

- conf/global.properties
- conf/global.properties.zimbrax
- src/java/com/zimbra/qa/soap/MailInjectTest.java
- Introduced global properties variable zimbraLMTPServer.name which would be LMTP server address (default lmtp proxy is zmc-lmtp)
- For Zimbra Cloud deployment, lmtp inject function gets LMTP server value as zimbraLMTPServer.name property 
- For Classic Zimbra, lmtp inject function gets LMTP server value as user's zimbraMailHost set by test  
See companion PR https://github.com/ZimbraOS/zm-docker-soap/pull/36 for changes in zm-docker-soap
**Testing Notes:**
Ran data/soapvalidator/Mail/LMTP/MimeBasic/Lmtp-Basic.xml testcase and verified that, lmtpinject is done on lmtp-proxy and test passed.
See below test run report:
[console.log](https://github.com/Zimbra/zm-soap-harness/files/4562631/console.log)
Below is the zmc-lmtp service log: …
> ZCS-9019: Modify lmtp inject function to use lmtp proxy instead of zimbraMailHost for Zimbra cloud soap tests

- build.xml
Update Existing ant target to support multiple Test Suites.
There is already a facility for this in java code i.e. 
if we pass multiple Test Suites using below Args
`-t smoke -t bhr`
Few examples to execute as below -
```
ant Run-SoapTestCore -DtestSuite1="smoke" -DtestSuite2="bhr"
ant Run-SoapTestCore -DtestSuite1="smoke" -DtestSuite2="functional"
ant Run-SoapTestCore -DtestSuite1="smoke" -DtestSuite2="negative"
```
**Note:** 
This may impact changes in execute test scripts to pass _testSuite1_ instead of _testSuite_ now and needs to be handled separately.
Please kindly check all comments before reviewing as this was being discussed and logic is now updated accordingly.
Related PR:
https://github.com/ZimbraOS/zm-continuous-integration/pull/62
> Update build.xml file to execute 2 different test suite together, i.e. "smoke, bhr", "smoke, functional", "bhr, functional" and so on

- data/soapvalidator/General/Password/Change-Password-DryRun.xml
Added ChangePassword tests for:
1. dryRun=1 with password not satisfying length rule - zimbraPasswordMinLength
2. dryRun=true with password not satisfying history rule - zimbraPasswordEnforceHistory
3. dryRun=1 with password rules - zimbraPasswordMinDigitsOrPuncs, zimbraPasswordMinUpperCaseChars, zimbraPasswordMinLowerCaseChars
4. dryRun=1 with valid password - should not change password, authToken not returned  in response
5. Without dryRun and valid password - should change password, authToken is returned  in response
> ZCS-9569: Added tests for ChangePassword with dryRun option

- data/soapvalidator/Briefcase/Briefcase-DocumentAction.xml
Add new testcases in Briefcase which include below requests:
DocumentActionRequest
GetWatchingItemsRequest
GetNotificationsRequest 
GetDocumentShareURLRequest
GetShareDetailsRequest
Testcases:
1) Added document in watch list using DocumentActionRequest and verified using GetWatchingItemsRequest and GetNotificationsRequest.
2) Saved document and get the URL which can be shared in Public.(Not verified the URL yet as this needs to be fixed as per the comment in ticket ZCD-9144).
3) Save Document and provide grant access to other user. Verified ACL on the same item using GetShareDetailsRequest.
Note: These testcases are valid only for zimbraX.
> ZCS-9493: Add SOAP automation tests for Octopus Briefcase APIs

- data/soapvalidator/Prefs/Filters/Bugs/Bug37018.xml
- data/soapvalidator/Prefs/Filters/Bugs/Bug77367.xml
- data/soapvalidator/Prefs/Filters/Conditions/Filter-AddressIn.xml
- data/soapvalidator/Prefs/Filters/Outgoing/ApplyOutgoingfilterRules-Basic.xml
- data/soapvalidator/Prefs/Filters/Priority/AddressBookTest.xml
- Fixed Bug77367.xml script which was failing due to incorrect search keywords used
- Other failures were due to timing issue where message got injected/sent immediately after filter was created. Added 10 seconds delay and verified that test are passing.
> ZCS-10056: Fixed Filter SOAP testcase script issues

- data/soapvalidator/Prefs/Filters/Sieve/Bug104314.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug104912.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug105636.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug106838.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug106845.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug106900.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug106993.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107212.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107330.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107379.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107562.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug28832.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug31446.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug71457.xml
- data/soapvalidator/Prefs/Filters/Sieve/EditHeaders.xml
- data/soapvalidator/Prefs/Filters/Sieve/MatchVariables.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1006-AsciiNumericNegativNumber.xml
- Used new COS instead of modifying existing COS
- Moved Modify Global config to setup script handled by zm-continuous-integration and commented out modifyconfig test steps. See companion PR https://github.com/ZimbraOS/zm-continuous-integration/pull/140
- Added delays for cases where sieve rule was not getting applied due to delay in lmtp
- Fixed other script issues
Note:
More Sieve tests are to be analysed and fixed.
> ZCS-10082: Fixed Sieve testcases - part1

- data/soapvalidator/Calendar/Appointments/CancelAppointmentRequest-RecurrenceDaily.xml
- data/soapvalidator/Calendar/Appointments/ForwardAppointmentInviteRequest-Basic.xml
- data/soapvalidator/Calendar/Appointments/Workflow/Calendar-SendInviteReply.xml
- data/soapvalidator/Calendar/Bugs/Bug26407.xml
- data/soapvalidator/Calendar/Bugs/Bug62417.xml
- data/soapvalidator/Calendar/Bugs/Bug71713.xml
Fixed following calendar bhr tests.
-build/temp/data/soapvalidator/Calendar/Bugs/Bug26407.xml----  Fixed : Need to put future date
-build/temp/data/soapvalidator/Calendar/Bugs/Bug62417.xml---   Fixed : Need to put future date   
-build/temp/data/soapvalidator/Calendar/Bugs/Bug71713.xml--      Fixed  Add Delay  of 20 sec  before GetMsgRequest and CounterAppointmentRequest.
-build/temp/data/soapvalidator/Calendar/Appointments/CancelAppointmentRequest-RecurrenceDaily.xml : Replaced smoke to bhr 
-build/temp/data/soapvalidator/Calendar/Appointments/ForwardAppointmentInviteRequest-Basic.xml : Add delay before GetAppointment Request.
-build/temp/data/soapvalidator/Calendar/Appointments/Workflow/Calendar-SendInviteReply.xml: : Replaced smoke to bhr
> ZCS-10083 fixed calendar bhr tests

- conf/skipped-tests-zimbrax.txt
- data/soapvalidator/Contacts/AutoComplete/Bug65081.xml
**Added following Contact/Calendar tests in skipped  file.:**
```
build/temp/data/soapvalidator/Calendar/Bugs/Bug33613.xml---Exiting bug-ZCS-6155
build/temp/data/soapvalidator/Calendar/Bugs/Bug34412.xml---Existing bug-ZCS-6155
build/temp/data/soapvalidator/Calendar/Bugs/Bug60181.xml---Test case is wrong
build/temp/data/soapvalidator/Contacts/AutoComplete/AutoCompleteRequest.xml  ---Existing bug :https://jira.corp.synacor.com/browse/ZCS-7999
build/temp/data/soapvalidator/Contacts/AutoComplete/Ranking/AutoComplete-Ranking.xml: Existing bug https://jira.corp.synacor.com/browse/ZCS-6163
build/temp/data/soapvalidator/Contacts/AutoComplete/Ranking/RankingActionRequest-Reset.xml Existing bug https://jira.corp.synacor.com/browse/ZCS-6163
build/temp/data/soapvalidator/Contacts/Bugs/Bug48742.xml …
```
> ZCS-10090 Fixed some Contacts script and added some tests in skipped file

- conf/skipped-tests-zimbrax.txt
- data/soapvalidator/Prefs/Filters/Sieve/Bug106870.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107221.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107222.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107321.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107355.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107361.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107381.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug107615.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1088-DetectSpacesInHeader.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1238-MatchVariables.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1287.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1845.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-2473-Matches-For-Malencoded-Header.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-273-EditHeader/AddHeader.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-273-EditHeader/DeleteHeader.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-273-EditHeader/Multirule.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-273-EditHeader/ReplaceHeader.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-283.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-560-NotificationEscape.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-863.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-892.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-893.xml
- Used new COS instead of modifying existing COS
- Moved Modify Global config to setup script handled by zm-continouus-integration and commented out modifyconfig test steps
- Fixed issues related to incorrect type used causing account creation to be skipped
- Skipped Custom-Header.xml test file as it would overwrite zimbraCustomMimeHeaderNameAllowed and cause other Sieve tests to fail
> ZCS-10091: Fixed Sieve testcases which were failing due to config/cos updates not reflecting to account

- data/soapvalidator/Prefs/Filters/Sieve/Bug106846.xml
- data/soapvalidator/Prefs/Filters/Sieve/Bug106900.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1287.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1378-ResetVarsBetweenFilters.xml
Performed below fixes:
- ZCS-1378-ResetVarsBetweenFilters test - was unsetting zimbraCustomMimeHeaderNameAllowed causing subsequent tests using zimbraCustomMimeHeaderNameAllowed values to fail. Commented mcf test as it is handled during installation.
- Did fixes in other tests related to incorrect Sieve attribute set at cos
> ZCS-10176: Fixed Sieve testcases

- conf/skipped-tests-zimbrax.txt
build/temp/data/soapvalidator/Admin/Bugs/Bug25398.xml | Existing bug | https://jira.corp.synacor.com/browse/ZCS-7258
-- | -- | --
build/temp/data/soapvalidator/Admin/Bugs/Bug74981.xml | Existing bug | https://jira.corp.synacor.com/browse/ZCS-5619
build/temp/data/soapvalidator/Admin/ExternalSharing/ExternalVirualAccountPolicy.xml | Script issue | Need to put dealy   after FolderActionRequest in "zimbraExternalSharingEnabled04"
build/temp/data/soapvalidator/Admin/ExternalSharing/ExternalVirualAccountWhiteList.xml | Script issue | Need to put dealy   after FolderActionRequest in   "zimbraExternalShareDomainWhitelistEnabled04"
build/temp/data/soapvalidator/Admin/General/GenCSRRequest.xml | Existing bug | https://jira.corp.synacor.com/browse/ZCS-5619 …
> added tests which are failing due to existing bug

- conf/skipped-tests-zimbrax.txt
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1286-SoapToSieve.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1390-SoapToSieve.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-375-SoapToSieve.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-840.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-842.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-865.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-870-NotificationReturnPathEscape.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-880.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-887-Immutable.xml
Fixed below Sieve scripts:
> build/temp/data/soapvalidator/Prefs/Filters/Sieve/ZCS-1286-SoapToSieve.xml - Fixed by adding delay after SendMsgRequest. Fixed 2 cases.
> 
> build/temp/data/soapvalidator/Prefs/Filters/Sieve/ZCS-1390-SoapToSieve.xml - Fixed by adding delay after SendMsgRequest. Fixed 5 cases.
> 
> build/temp/data/soapvalidator/Prefs/Filters/Sieve/ZCS-375-SoapToSieve.xml - Fixed by adding delay after SendMsgRequest. Fixed 1 case.
> 
> build/temp/data/soapvalidator/Prefs/Filters/Sieve/ZCS-500.xml - Skipped this test. ModifyFilterRules are performed on domain/cos/server. Will not modify ldap cache for accounts on non-admin mailbox pod.
> 
> build/temp/data/soapvalidator/Prefs/Filters/Sieve/ZCS-559-EscapeSeq.xml - Reported ZCS-10352 and skipped test
> 
> …
> ZCS-10350: Fixed Sieve test script issues, skipped known issues

- data/soapvalidator/Admin/Accounts/account_migration.xml
Added test for Zimbra to zimbra account migration:ZCS9805:
AuthRequest                                         151          2             75
CreateAccountRequest                                223          1            223
SearchRequest                                       256          1            256
PingRequest                                         375          1            375
FetchAllRemoteAccountsRequest                      4845          1           4845
ValidateRemoteZimbraConnectionRequest                88          1             88
MigrateUsersDataRequest                              57 …
> Added test for Zimbra to zimbra account migration:ZCS9805

- data/soapvalidator/Admin/General/RecalculateMailboxCountsRequest_10391.xml
Added Automation for ZCS-10391.
Result:
-------------------FILE INFO---------------------
XML: build/temp/data/soapvalidator/Admin/General/RecalculateMailboxCountsRequest1.xml
AuthRequest                                         303          4             75
CreateAccountRequest                                127          1            127
PingRequest                                         296          1            296
GetFolderRequest                                    165          2             82
RecalculateMailboxCountsRequest                     137          1            137 …
> Verify Total Msg Count Before and After hitting RecalculateMailboxCountsRequest API

- data/soapvalidator/Briefcase/Briefcase-DocumentAction.xml
/opt/soap/zm-soap-harness/build/temp/data/soapvalidator/Briefcase/Briefcase-DocumentAction.xml
Tests is failing since long time.
At many places file name for attachment are wrong .
Now it is passing.
> Fix Briefcase-DocumentAction related tests

- data/soapvalidator/Auth/ForgetPassword/ResetAccountPassword.xml
I have added soap automation for ResetAccountPasswordRequest  API.
Result:
-------------------FILE INFO---------------------
XML: build/temp/data/soapvalidator/MailClient/ForgetPassword/ResetAccountPassword.xml
AuthRequest                                         542          3            180
CreateAccountRequest                                242          2            121
SearchRequest                                     21139          1          21139
ResetAccountPasswordRequest                         106          1            106
GetMsgRequest                                        73          1 …
> Added soap automation for ResetAccountPasswordRequest API

- conf/skipped-tests-zimbrax.txt
- data/soapvalidator/Auth/ForgetPassword/ZCS-4798.xml
#build/temp/data/soapvalidator/Auth/ForgetPassword/ResetPassword-ZCS-4802.xml
#build/temp/data/soapvalidator/Auth/ForgetPassword/ZCS-4798.xml
While executing Soap automation these 2 files were skipped previously, due to this we were missing issue mentioned in ZCS-10427.
Now these 2 files are included in run .
See the recent run result.
[java] Test Cases Executed:6
[java] Pass:5
[java] Fail:1
[java] Script Errors:0
[java]
[java] These tests had failures:
[java]     /opt/soap/zm-soap-harness/build/temp/data/soapvalidator/Auth/ForgetPassword/ZCS-4798.xml
>  Removed all forget password related tests from skip file

- data/soapvalidator/Folders/Bugs/Bug10137.xml
-------------------FILE INFO---------------------
XML: build/temp/data/soapvalidator/Folders/Bug10137.xml
AuthRequest                                         183          2             91
CreateAccountRequest                                135          1            135
PingRequest                                         439          1            439
GetFolderRequest                                     77          1             77
FolderActionRequest                                 195          2             97
CreateFolderRequest                                 320          2            160 …
> Added automation zcs10137 : Trash" with nested folders can not be emptied.

- data/soapvalidator/Auth/ForgetPassword/ResetPassword-ZCS-4802.xml
- data/soapvalidator/Mail/Bugs/Bug70165.xml
- data/soapvalidator/Mail/Bugs/Bug97339.xml
- data/soapvalidator/Mail/LMTP/AOL/AOL-MIME-Basic.xml
- data/soapvalidator/Prefs/Identities/Assign-Identity.xml
- data/soapvalidator/Prefs/Identities/Attachment-Identity.xml
- data/soapvalidator/Search/Bugs/Bug62605.xml
Fixed following tests from BHR.
```
data/soapvalidator/Auth/ForgetPassword/ResetPassword-ZCS-4802.xml
data/soapvalidator/Mail/Bugs/Bug70165.xml
data/soapvalidator/Mail/Bugs/Bug97339.xml
data/soapvalidator/Mail/LMTP/AOL/AOL-MIME-Basic.xml
data/soapvalidator/Prefs/Identities/Assign-Identity.xml
data/soapvalidator/Prefs/Identities/Attachment-Identity.xml
data/soapvalidator/Search/Bugs/Bug62605.xml
```
> Fixed skipped and failure tests

- data/soapvalidator/Prefs/Filters/Sieve/ZCS-1850.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-860-EditHeader.xml
Fixed tests in ZCS-1850.xml and ZCS-860-EditHeader.xml
Created new cos with zimbraSieveEditHeaderEnabled=TRUE and used in tests. 
Marked ZCS-1850_rule2 and ZCS-1850_rule3 tests as functional - cos/domain modification will not be updated on both mailbox pods immediately.
> ZCS-10693: Sieve soap testcase fixes

- data/soapvalidator/Search/Contacts/Search-Contact-10799.xml
Issue:
Search is broken when contact having single quotes in FirstName/LastName/EmailId.
This issue has been fixed now and added automated test case for the same issue
> Added test case for search contact which having single quotes in it

- data/soapvalidator/Prefs/Filters/Sieve/Bug106349.xml
- data/soapvalidator/Prefs/Filters/Sieve/EditHeader-Shared-And-Cloned.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-500.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-842.xml
- data/soapvalidator/Prefs/Filters/Sieve/ZCS-860-EditHeader.xml
Fixed tests that were failing or throwing exception due to setup test cases being skipped and not setting attributes that were referenced in finally block.
> ZCS-11635: Fixed Sieve tests that were failing due to attributes not getting set 

- data/soapvalidator/Admin/AdminSearch/SearchDirectoryRequest.xml
Requirement:
Added following test cases for count on SearchDirectoryRequest:
1. limit="-1"
2. limit="1000" maxResults="1"
3. limit="0" maxResults="-1"
4. limit="0" maxResults="1000"
> ZBUG-733 Added testcases for limit="-1" |maxResults attributes in SearchDirectoryRequest

- data/soapvalidator/Briefcase/Briefcase-ZimbraFileUploadMaxSize.xml
**Issue:** WebClient and AdminConsole both are not loading if we set the value of zimbraFileUploadMaxSize greater than 2147483647
**Automation:** 
- Modified the attribute value of zimbraFileUploadMaxSize to 20 GB.
- Restart the mailbox
- Added the test cases for Briefcase upload using different types of files.
- Revert the attribute value of zimbraFileUploadMaxSize to the original.
> ZBUG-3204: added soap automation for zimbraFileUploadMaxSize

- data/soapvalidator/Auth/JWT/JWT-ZCS-2478.xml
- data/soapvalidator/Contacts/Contact-Modify-Group-Ref.xml
- data/soapvalidator/Folders/Bugs/Bug31113.xml
**Fixed below test cases:**
/opt/qa/soapvalidator/data/soapvalidator/Contacts/Contact-Modify-Group-Ref.xml --> Fixed request in test case
/opt/qa/soapvalidator/data/soapvalidator/Folders/Bugs/Bug31113.xml --> Fixed file name in test case
/opt/qa/soapvalidator/data/soapvalidator/Auth/JWT/JWT-ZCS-2478.xml --> deprecated failing test cases because of open issue
**`XML: C:\soap\zm-soap-harness\data\soapvalidator\Folders\Bugs\Bug31113.xml**
AuthRequest                                         216          3             72
CreateAccountRequest                               5439          2           2719 …
> ZCS-14392:Fix Soap harness failures in execution on OCI VM

- data/soapvalidator/Admin/ExternalStore/VerifyStoreManagerRequest.xml
- data/soapvalidator/Auth/CustomAuth/CustomAuth.xml
Few tests used custom jars built with old log4j and caused issues after copy on mailbox server. Deprecated tests till we use updated custom jars.
> ZCS-14799: Deprecated tests blocking soap execution

- data/soapvalidator/Auth/JWT/JWT-ZCS-2478.xml
Fixed test case type to "bhr-temp" instead of "bhr-tbd" in data/soapvalidator/Auth/JWT/JWT-ZCS-2478.xml
> ZCS-14776: Fixed test case type to bhr-temp instead of bhr-tbd

- data/soapvalidator/Auth/JWT/JWT-ZCS-2478.xml
- data/soapvalidator/Calendar/Appointments/CancelAppointmentRequest-Basic.xml
- data/soapvalidator/Calendar/Appointments/CreateAppointmentRequest-Private.xml
- data/soapvalidator/REST/Mail/Post/Basic.xml
Fixed below test cases:
- data/soapvalidator/Calendar/Appointments/CreateAppointmentRequest-Private.xml
- data/soapvalidator/Calendar/Appointments/CreateAppointmentRequest-Reminder.xml
Changed time and verification method so that tests will be executed on all timezone
- /opt/qa/soapvalidator/data/soapvalidator/REST/Mail/Post/Basic.xml
Updated bug id in the script
> ZCS-14776: Fix Soap harness failures in execution on OCI VM

- utils/run_and_monitor_soap.sh
**ZCS-14882: Use curl for sending notification emails. Add build info and other details in the email.**
- Using curl instead of sendmail command for sending the notification emails
- Added more details about the builds in the emails.
- Using email in HTML format to make it look good in the inbox.
- Resolved incorrect editing of global.properties file.
**Note -**
- Env variables `ENV_MAIL_FROM`, `ENV_MAIL_PASSWORD` and `ENV_SMTP_SERVER` Must be set on the server for Notification emails to be sent out.
> ZCS-14882: Use curl for sending notification emails. Add build info and other details in the email.

- conf/skipped-tests-zimbrax.txt
- data/soapvalidator/Mail/Persona/SendMailUsingDistributionListPersona.xml
- data/soapvalidator/Search/Bugs/Bug12539.xml
- data/soapvalidator/Search/Bugs/Bug78001.xml
Fixed/Skipped the following test cases which are failing in master workflow of ZoK:
Following tests have been added to skip list as they are failing because of application issues ZCS-14652 and ZCS-14997
`build/temp/data/soapvalidator/Admin/DistributionList/Bugs/69486.xml
build/temp/data/soapvalidator/Admin/DistributionList/Bugs/Bug68891.xml
build/temp/data/soapvalidator/Admin/DistributionList/Bugs/Bug72791.xml
build/temp/data/soapvalidator/Admin/DistributionList/DL-SendToDistList.xml
build/temp/data/soapvalidator/Admin/DistributionList/Distributionlist-Action-Add-Remove-Member.xml
build/temp/data/soapvalidator/Admin/DistributionList/Distributionlist-Action-Delete.xml
build/temp/data/soapvalidator/Admin/DistributionList/Distributionlist-Action-Modify.xml …
> ZCS-14952: Fixed the failing BHR test cases in master workflow of ZoK
